/**
 * Battle arena types — the shared state for an active player-vs-player (or
 * player-vs-barbarians) battle. One battle may be active at a time per game.
 *
 * This is entirely new: the old Java backend left battle as an open TODO and
 * never implemented arena tracking. See docs/agents/decisions.md.
 */

import type { Rotation } from './board.js'
import type { UnitItem } from './item.js'

/** Which side of the arena. The initiator is always 'attacker'. */
export type BattleSideId = 'attacker' | 'defender'

/**
 * One participant in a battle. Barbarians are their own side: the player to
 * the attacker's left moves for them. Their units come from
 * `Playerhand.barbarians` rather than the hand.
 */
export interface BattleSide {
  readonly kind: 'player' | 'barbarians'
  /**
   * The player who controls this side. For barbarians, this is the player to
   * the attacker's left.
   */
  readonly playerId: string
}

/**
 * A unit standing in the arena.
 *
 * `unit` is a snapshot taken at placement — the card is face-up from that
 * moment on, so no projection needs to reach into a hidden hand to render it.
 *
 * `attack` and `health` are user-entered, not the card's printed values.
 * Units can be upgraded by techs and wonders without new artwork, so players
 * always type in the current combat stats. They are seeded from the card
 * values as a convenience, but are fully editable.
 *
 * `health` tracks remaining HP; it starts at the entered value and decreases
 * as damage is taken. It may be increased (healing). Both attack and health
 * may be edited by any game member, with every change logged.
 */
export interface ArenaUnit {
  /** Unique id for this slot — not the card id. Generated from `nextId`. */
  readonly id: string
  /** Which side this unit belongs to. */
  readonly side: BattleSideId
  /**
   * Column index. Explicit integer so that killing a unit leaves a gap rather
   * than silently shifting survivors into new matchups. Two units on the same
   * `position` — one per side — face each other. A unit with no opponent on
   * its position is holding an open front.
   */
  readonly position: number
  /** Snapshot of the card at the moment it was placed (for the image and name). */
  readonly unit: UnitItem
  /** Current attack value (user-entered, seeded from card). */
  readonly attack: number
  /** Current remaining health (user-entered, seeded from card). */
  readonly health: number
  /** The playerId of whoever dragged the card into the arena. */
  readonly placedBy: string
  /**
   * Visual rotation of the card, in 90° steps. The physical card prints one
   * unit level per edge (e.g. Archer/Catapult/Cannon/Mobile Artillery on an
   * Artillery card); rotating it is how a player shows which level the unit
   * is currently playing at. Purely cosmetic — it does not touch `attack` or
   * `health`, which stay independently user-entered.
   */
  readonly rotation: Rotation
  /**
   * Marked, not removed, when killed — so a kill can be undone (issue #71)
   * right up until the battle ends. The source card is only actually
   * discarded, and this unit dropped from the arena, when the battle ends
   * with this still `true`.
   */
  readonly killed: boolean
}

/** The one battle that may be active in a game at a time. */
export interface Battle {
  /** Unique id — generated by `nextId(state.rng)`. */
  readonly id: string
  readonly attacker: BattleSide
  readonly defender: BattleSide
  /**
   * Whose battle turn it is. Advisory only — not enforced server-side,
   * consistent with how `NOT_YOUR_TURN` is handled elsewhere in the codebase.
   * The UI greys out the "end battle turn" button when it is not your turn.
   */
  readonly turn: BattleSideId
  readonly arena: readonly ArenaUnit[]
}

/** Derived totals per side — computed in `toPlayerView`, never stored. */
export interface BattleSideSummary {
  readonly side: BattleSideId
  readonly kind: 'player' | 'barbarians'
  readonly playerId: string
  /** Display name: the username for players, "Barbarians" for the barbarian side. */
  readonly label: string
  readonly unitCount: number
  readonly totalHealth: number
  readonly totalAttack: number
  /**
   * `PlayerStats.combat` for player sides (may be negative — it is the only
   * signed stat). Barbarians have no combat bonus; their value is always 0.
   */
  readonly combatBonus: number
}
