/**
 * The board.
 *
 * Replaces the Google Presentation hack: the old system stored a link to a
 * slide in `PBF.mapLink` and let a moderator move pieces around by hand.
 *
 * The geometry comes from `Civilization/Moderator/4v4 Map Template.pptx`:
 * 16 x 16 squares labelled A-P and 1-16, assembled from 4 x 4 map tiles of
 * 375 x 375 pixels. That makes a square 375 / 4 ~ 94 pixels, which is exactly
 * the size of the city, building and city-state pieces in the same folder.
 *
 * Pieces sit at free pixel coordinates rather than snapping to squares. That is
 * how the PowerPoint template was used, and it is what makes it possible to
 * stack several pieces in one square or park one half outside the edge.
 *
 * Below the map is a band of player areas, one per player. Dropping a piece
 * there tidies it into the next free slot, so a pile of collected huts reads as
 * a row rather than a heap.
 */

import boardAssets from '../data/board-assets.json' with { type: 'json' }

/** Edge length of one square, in the board's own coordinate system. */
export const SQUARE_SIZE = 94

/** A map tile covers 4 x 4 squares. */
export const TILE_SQUARES = 4

/** 4 x 4 map tiles, as in the four-player template. */
export const DEFAULT_COLUMNS = 16
export const DEFAULT_ROWS = 16

/** Height of the player-area band, in squares. */
export const DEFAULT_AREA_ROWS = 4

/** Blank space between the map and the player areas, in squares. */
export const AREA_GAP_SQUARES = 1

/** Blank space between the culture track and the map, in squares. */
export const CULTURE_GAP_SQUARES = 1

/** Room for the name written across the top of a player area, in pixels. */
export const AREA_LABEL_HEIGHT = 26

/** Column labels from the template: A through P. */
export const COLUMN_LABELS = Array.from({ length: DEFAULT_COLUMNS }, (_, index) =>
  String.fromCharCode(65 + index),
)

export type BoardAssetCategory =
  | 'figure'
  | 'resource'
  | 'marker'
  | 'city'
  | 'building'
  /** The civilizations' starting tiles, one per civ. */
  | 'civtile'
  /** The numbered exploration tiles, plus the tile back. */
  | 'tile'
  /** Leader portraits, which mark a player's place on the culture track. */
  | 'leader'

/** Pieces can face four ways. Degrees, clockwise. */
export type Rotation = 0 | 90 | 180 | 270

export const ROTATIONS: readonly Rotation[] = [0, 90, 180, 270]

export function nextRotation(rotation: Rotation, clockwise = true): Rotation {
  const index = ROTATIONS.indexOf(rotation)
  const step = clockwise ? 1 : ROTATIONS.length - 1
  return ROTATIONS[(index + step) % ROTATIONS.length] as Rotation
}

/** A kind of piece that can be put on the board, taken from the images on disk. */
export interface BoardAsset {
  /** Stable key, for example "figures/redarmy". */
  readonly id: string
  readonly category: BoardAssetCategory
  /** Path under the client's /board/, for example "figures/redarmy.png". */
  readonly path: string
  readonly label: string
  readonly width: number
  readonly height: number
}

/** The culture track backdrop: a path under /board/ and its natural size. */
export interface CultureTrackImage {
  readonly path: string
  readonly width: number
  readonly height: number
}

interface BoardAssetFile {
  readonly cultureTrack: CultureTrackImage
  readonly assets: readonly BoardAsset[]
}

/** The culture track image, drawn across the top of the board. */
export const CULTURE_TRACK: CultureTrackImage = (boardAssets as BoardAssetFile).cultureTrack

/**
 * Every known kind of piece, generated by `tools/board-assets.ps1` from the
 * images in `Civilization/Moderator`. The manifest lives in the engine rather
 * than the client because the server has to be able to reject a piece pointing
 * at an unknown file.
 */
export const BOARD_ASSETS: readonly BoardAsset[] = (boardAssets as BoardAssetFile).assets

const ASSETS_BY_ID = new Map(BOARD_ASSETS.map((asset) => [asset.id, asset]))

export function findBoardAsset(assetId: string): BoardAsset | undefined {
  return ASSETS_BY_ID.get(assetId)
}

export function boardAssetsByCategory(category: BoardAssetCategory): readonly BoardAsset[] {
  return BOARD_ASSETS.filter((asset) => asset.category === category)
}

/** A piece lying on the board. */
export interface BoardPiece {
  readonly id: string
  readonly assetId: string
  /** Copied from the manifest on placement so the client needs no lookup. */
  readonly path: string
  readonly label: string
  readonly category: BoardAssetCategory
  /** Left and top edge in board coordinates. */
  readonly x: number
  readonly y: number
  readonly width: number
  readonly height: number
  /**
   * Rotation clockwise. Map tiles carry an arrow showing which way the tile
   * goes, so they have to turn. Every piece can turn, for consistency.
   */
  readonly rotation: Rotation
  /** Who put it there. Anyone may move it afterwards. */
  readonly placedBy: string | null
}

// ---------------------------------------------------------------------------
// History
// ---------------------------------------------------------------------------

/**
 * One change to the pieces on the board.
 *
 * Each variant carries exactly what is needed to apply it forwards and to take
 * it back, so the whole game can be stepped through and any change undone. A
 * generic before/after diff was tempting but would record the entire stack
 * every time a piece is brought to the front.
 */
export type BoardChange =
  /** `onTop` is false for map tiles, which slide underneath everything else. */
  | { readonly kind: 'place'; readonly piece: BoardPiece; readonly onTop: boolean }
  | { readonly kind: 'remove'; readonly piece: BoardPiece; readonly index: number }
  | {
      readonly kind: 'move'
      readonly pieceId: string
      readonly from: { readonly x: number; readonly y: number }
      readonly to: { readonly x: number; readonly y: number }
      /** Where it sat in the stack before; moving also brings it to the top. */
      readonly fromIndex: number
    }
  | {
      readonly kind: 'rotate'
      readonly pieceId: string
      readonly from: Rotation
      readonly to: Rotation
    }
  | {
      readonly kind: 'reorder'
      readonly pieceId: string
      readonly fromIndex: number
      readonly toTop: boolean
    }
  | { readonly kind: 'clear'; readonly pieces: readonly BoardPiece[] }

export interface BoardHistoryEntry {
  readonly id: string
  /** ISO timestamp, supplied by the caller since the engine stays pure. */
  readonly at: string | null
  readonly playerId: string
  readonly username: string
  /** Ready to show in a list: "cash1981 moved Red army from E4 to H8". */
  readonly description: string
  readonly change: BoardChange
  /**
   * How many game-log entries existed once this change was made. Stepping back
   * through history uses it to trim the log to what was known at the time.
   */
  readonly logLength: number
}

/**
 * The board. The order of `pieces` IS the stacking order: the last element is
 * drawn on top. That removes the need for a z-index, and "bring to front" is
 * just a move to the end of the list.
 */
export interface Board {
  readonly columns: number
  readonly rows: number
  readonly squareSize: number
  /** Height of the player-area band below the map, in squares. */
  readonly areaRows: number
  readonly pieces: readonly BoardPiece[]
  readonly history: readonly BoardHistoryEntry[]
}

export function createBoard(
  columns = DEFAULT_COLUMNS,
  rows = DEFAULT_ROWS,
  areaRows = DEFAULT_AREA_ROWS,
): Board {
  return { columns, rows, squareSize: SQUARE_SIZE, areaRows, pieces: [], history: [] }
}

export const boardWidth = (board: Board): number => board.columns * board.squareSize
/** Height of the map itself, not counting the track or the player areas. */
export const mapHeight = (board: Board): number => board.rows * board.squareSize

/**
 * Height of the culture track band. The track image is drawn across the full
 * width of the map, so its height follows from its own aspect.
 */
export const cultureTrackHeight = (board: Board): number =>
  Math.round((boardWidth(board) * CULTURE_TRACK.height) / CULTURE_TRACK.width)

/** Top edge of the map. The culture track sits above it. */
export const mapTop = (board: Board): number =>
  cultureTrackHeight(board) + CULTURE_GAP_SQUARES * board.squareSize

/** Top edge of the player-area band. */
export const areaBandTop = (board: Board): number =>
  mapTop(board) + mapHeight(board) + AREA_GAP_SQUARES * board.squareSize

/** Full height of the drag surface: track, map and player areas, with gaps. */
export const boardHeight = (board: Board): number =>
  areaBandTop(board) + board.areaRows * board.squareSize

// ---------------------------------------------------------------------------
// The culture track
// ---------------------------------------------------------------------------

/**
 * The spaces of the culture track, measured off the artwork by finding the dark
 * divider columns in `DoC/PBF Modding Material/culture track.png`.
 *
 * There are 27 spaces between Start and Culture Victory, in four sections of
 * 7, 7, 7 and 6 — one per culture event — separated by a wide pillar. Within a
 * section the spaces are even, so each is given as the pixel span of its
 * section in the source image and divided up.
 *
 * Neither Java nor the AngularJS app had a culture track. It is a marker only:
 * nothing here enforces what it costs to advance or what happens at a
 * threshold, because those rules are not in the ported source.
 */
const CULTURE_SECTIONS: readonly { readonly from: number; readonly to: number; readonly cells: number }[] = [
  { from: 116, to: 907, cells: 7 },
  { from: 936, to: 1725, cells: 7 },
  { from: 1753, to: 2540, cells: 7 },
  { from: 2569, to: 3252, cells: 6 },
]

/** Spaces on the track, numbered 1 to 27. */
export const CULTURE_TRACK_CELLS = CULTURE_SECTIONS.reduce(
  (total, section) => total + section.cells,
  0,
)

/** Centre of each space as a fraction of the track image's width. */
const CULTURE_CELL_FRACTIONS: readonly number[] = CULTURE_SECTIONS.flatMap((section) => {
  const width = (section.to - section.from) / section.cells
  return Array.from(
    { length: section.cells },
    (_, index) => (section.from + (index + 0.5) * width) / CULTURE_TRACK.width,
  )
})

/** Bottom edge of the culture track band. */
export const cultureBandBottom = (board: Board): number => cultureTrackHeight(board)

/** Whether a point falls in the culture track band. */
export const inCultureBand = (board: Board, y: number): boolean =>
  y >= 0 && y < cultureBandBottom(board)

/**
 * Centre of one space, in board coordinates. `step` is 1-based, matching the
 * numbering players use when they say "I am on 12".
 */
export function cultureCellCenter(
  board: Board,
  step: number,
): { readonly x: number; readonly y: number } {
  const index = Math.min(Math.max(Math.round(step), 1), CULTURE_TRACK_CELLS) - 1
  const fraction = CULTURE_CELL_FRACTIONS[index] ?? 0
  return {
    x: Math.round(fraction * boardWidth(board)),
    y: Math.round(cultureTrackHeight(board) / 2),
  }
}

/** The space a piece sits on, by its centre, or null when off the track. */
export function cultureStepOf(board: Board, piece: BoardPiece): number | null {
  const centreY = piece.y + piece.height / 2
  if (!inCultureBand(board, centreY)) return null

  const centreX = (piece.x + piece.width / 2) / boardWidth(board)
  let best = 0
  let bestDistance = Number.POSITIVE_INFINITY
  for (const [index, fraction] of CULTURE_CELL_FRACTIONS.entries()) {
    const distance = Math.abs(fraction - centreX)
    if (distance < bestDistance) {
      bestDistance = distance
      best = index
    }
  }
  return best + 1
}

/**
 * Where a piece dropped on the culture track belongs: centred on the nearest
 * space. Markers already on that space are stepped down a row so several
 * players on the same space stay readable rather than hiding each other.
 */
export function cultureSlot(
  board: Board,
  piece: BoardPiece,
  x: number,
  y: number,
  others: readonly BoardPiece[],
): readonly [x: number, y: number] {
  const step = cultureStepOf(board, { ...piece, x, y }) ?? 1
  const centre = cultureCellCenter(board, step)
  const left = Math.round(centre.x - piece.width / 2)

  const band = cultureTrackHeight(board)
  const lanes = Math.max(1, Math.floor(band / piece.height))
  const sharing = others.filter(
    (other) => other.id !== piece.id && cultureStepOf(board, other) === step,
  ).length

  const lane = sharing % lanes
  const top = Math.round((band - lanes * piece.height) / 2 + lane * piece.height)
  return [left, top]
}

// ---------------------------------------------------------------------------
// Player areas
// ---------------------------------------------------------------------------

/** One player's own space below the map. */
export interface BoardArea {
  readonly playerId: string
  readonly username: string
  readonly color: string | null
  readonly x: number
  readonly y: number
  readonly width: number
  readonly height: number
}

/** The bit of an area that holds pieces, below the name. */
export const areaSlotRegion = (
  area: BoardArea,
): { readonly x: number; readonly y: number; readonly width: number; readonly height: number } => ({
  x: area.x,
  y: area.y + AREA_LABEL_HEIGHT,
  width: area.width,
  height: area.height - AREA_LABEL_HEIGHT,
})

/** Just enough of a player to lay out their area. */
export interface AreaPlayer {
  readonly playerId: string
  readonly username: string
  readonly color: string | null
  readonly playernumber: number
}

/**
 * Lays the players out in a band below the map, in player-number order, one
 * equal-width area each. Derived rather than stored, so it cannot drift out of
 * step when someone joins or withdraws.
 */
export function playerAreas(
  board: Board,
  players: readonly AreaPlayer[],
): readonly BoardArea[] {
  if (players.length === 0) return []

  const gutter = 8
  const top = areaBandTop(board)
  const height = board.areaRows * board.squareSize
  const total = boardWidth(board)
  const width = (total - gutter * (players.length - 1)) / players.length

  return [...players]
    .sort((a, b) => a.playernumber - b.playernumber || a.username.localeCompare(b.username))
    .map((player, index) => ({
      playerId: player.playerId,
      username: player.username,
      color: player.color,
      x: Math.round(index * (width + gutter)),
      y: top,
      width: Math.round(width),
      height,
    }))
}

/** The area a point falls inside, if any. */
export function areaAt(
  areas: readonly BoardArea[],
  x: number,
  y: number,
): BoardArea | undefined {
  return areas.find(
    (area) =>
      x >= area.x && x < area.x + area.width && y >= area.y && y < area.y + area.height,
  )
}

/**
 * The next free slot in a player area, read row by row.
 *
 * Pieces dropped in an area tidy themselves into a grid, so five collected huts
 * line up instead of piling on top of each other. Falls back to the drop point
 * when the area is full.
 */
export function nextFreeSlot(
  board: Board,
  area: BoardArea,
  pieces: readonly BoardPiece[],
  fallback: { readonly x: number; readonly y: number },
): readonly [x: number, y: number] {
  const region = areaSlotRegion(area)
  const slot = board.squareSize
  const columns = Math.max(1, Math.floor(region.width / slot))
  const rows = Math.max(1, Math.floor(region.height / slot))

  const taken = new Set(
    pieces
      .filter(
        (piece) =>
          piece.x >= region.x &&
          piece.x < region.x + region.width &&
          piece.y >= region.y &&
          piece.y < region.y + region.height,
      )
      .map((piece) => {
        const column = Math.round((piece.x - region.x) / slot)
        const row = Math.round((piece.y - region.y) / slot)
        return `${column},${row}`
      }),
  )

  for (let row = 0; row < rows; row++) {
    for (let column = 0; column < columns; column++) {
      if (!taken.has(`${column},${row}`)) {
        return [region.x + column * slot, region.y + row * slot]
      }
    }
  }
  return [fallback.x, fallback.y]
}

// ---------------------------------------------------------------------------
// Geometry helpers
// ---------------------------------------------------------------------------

/**
 * Keeps a piece inside the surface. Half of it may hang over the edge, so a
 * marker can sit in the margin without disappearing.
 */
export function clampToBoard(
  board: Board,
  x: number,
  y: number,
  width: number,
  height: number,
): readonly [x: number, y: number] {
  const clamp = (value: number, max: number): number => Math.min(Math.max(value, 0), max)
  return [
    clamp(Math.round(x), boardWidth(board) - width / 2),
    clamp(Math.round(y), boardHeight(board) - height / 2),
  ]
}

/** The square a piece sits in, by its centre. `null` when off the map. */
export function squareOf(board: Board, piece: BoardPiece): string | null {
  const column = Math.floor((piece.x + piece.width / 2) / board.squareSize)
  const row = Math.floor((piece.y + piece.height / 2 - mapTop(board)) / board.squareSize)
  if (column < 0 || column >= board.columns || row < 0 || row >= board.rows) return null
  return `${COLUMN_LABELS[column] ?? '?'}${row + 1}`
}

/** Where a piece is, in words: a culture space, a map square or a player's area. */
export function locationOf(
  board: Board,
  areas: readonly BoardArea[],
  piece: BoardPiece,
): string {
  const step = cultureStepOf(board, piece)
  if (step !== null) return `culture ${step}`

  const square = squareOf(board, piece)
  if (square !== null) return square

  const area = areaAt(areas, piece.x + piece.width / 2, piece.y + piece.height / 2)
  if (area !== undefined) return `${area.username}'s area`

  return 'off the board'
}

export function findPiece(board: Board, pieceId: string): BoardPiece | undefined {
  return board.pieces.find((piece) => piece.id === pieceId)
}

// ---------------------------------------------------------------------------
// Map tiles: slots, corners and orientation
// ---------------------------------------------------------------------------

/** Number of 4 x 4 slots along each edge. Sixteen squares gives four. */
export const blockColumns = (board: Board): number =>
  Math.floor(board.columns / TILE_SQUARES)
export const blockRows = (board: Board): number => Math.floor(board.rows / TILE_SQUARES)

/** Top-left corner of the slot at (block column, block row), in pixels. */
export function blockOrigin(
  board: Board,
  blockColumn: number,
  blockRow: number,
): readonly [x: number, y: number] {
  const size = TILE_SQUARES * board.squareSize
  return [blockColumn * size, mapTop(board) + blockRow * size]
}

/**
 * Where a civilization's starting tile goes, and which way it faces.
 *
 * Player 1 takes the top-left slot (A1-D4), 2 the top-right, 3 the
 * bottom-right and 4 the bottom-left, matching the example board.
 *
 * Starting tiles carry an arrow showing which way the tile goes, and it should
 * point in towards the middle. In the image files the arrow points down —
 * checked against japan.jpg and germany.png. Turning clockwise carries it
 * round: 0 degrees points down, which suits the top-left slot; 90 points left,
 * which suits the top-right; and so on.
 *
 * The tile can be turned freely afterwards, so this is a starting point rather
 * than a constraint.
 */
export function startingCorner(
  board: Board,
  playernumber: number,
): { readonly x: number; readonly y: number; readonly rotation: Rotation } {
  const lastColumn = blockColumns(board) - 1
  const lastRow = blockRows(board) - 1

  const corners: readonly { blockColumn: number; blockRow: number; rotation: Rotation }[] = [
    { blockColumn: 0, blockRow: 0, rotation: 0 },
    { blockColumn: lastColumn, blockRow: 0, rotation: 90 },
    { blockColumn: lastColumn, blockRow: lastRow, rotation: 180 },
    { blockColumn: 0, blockRow: lastRow, rotation: 270 },
  ]

  // playernumber is 1-based; more than four players share the corners again
  const corner = corners[
    (Math.max(playernumber, 1) - 1) % corners.length
  ] as (typeof corners)[number]
  const [x, y] = blockOrigin(board, corner.blockColumn, corner.blockRow)
  return { x, y, rotation: corner.rotation }
}

/**
 * First free 4 x 4 slot, read row by row. Used when an exploration tile is
 * drawn: the system does not know which area the player is exploring, so the
 * tile lands somewhere there is room and is dragged into place from there.
 *
 * Falls back to the top-left slot when the map is full.
 */
export function firstFreeBlock(board: Board): readonly [x: number, y: number] {
  const size = TILE_SQUARES * board.squareSize
  const top = mapTop(board)
  const taken = new Set(
    board.pieces
      .filter((piece) => piece.category === 'tile' || piece.category === 'civtile')
      .map((piece) => `${Math.round(piece.x / size)},${Math.round((piece.y - top) / size)}`),
  )

  for (let row = 0; row < blockRows(board); row++) {
    for (let column = 0; column < blockColumns(board); column++) {
      if (!taken.has(`${column},${row}`)) return blockOrigin(board, column, row)
    }
  }
  return blockOrigin(board, 0, 0)
}

/**
 * Civilization name in the spreadsheet to the file name of its starting tile.
 *
 * The names do not line up: the sheet says "Americans" while the image is
 * called "america.png". The mapping is therefore written out in full rather
 * than guessed.
 */
const CIV_TILE_BY_NAME: Readonly<Record<string, string>> = {
  Americans: 'tiles/america',
  Arabs: 'tiles/arabia',
  Aztecs: 'tiles/Aztec',
  Chinese: 'tiles/china',
  Egyptians: 'tiles/egypt',
  England: 'tiles/England',
  French: 'tiles/France',
  Germans: 'tiles/germany',
  Greeks: 'tiles/greece',
  Indians: 'tiles/india',
  Japanese: 'tiles/japan',
  Mongols: 'tiles/mongolia',
  Romans: 'tiles/rome',
  Russians: 'tiles/russia',
  Spanish: 'tiles/spain',
  Zulu: 'tiles/Zulu',
}

export function civTileAssetId(civName: string): string | undefined {
  return CIV_TILE_BY_NAME[civName]
}

/**
 * Civilization name to the leader whose portrait marks its place on the
 * culture track.
 *
 * Neither Java nor the AngularJS app had leaders; the artwork under
 * Moderator/leaders was only ever used on the physical board. The file names
 * are a mix of leader and nation ("Genghis", but "japanese"), and of casing, so
 * the mapping is written out rather than derived.
 */
const LEADER_BY_CIV: Readonly<Record<string, string>> = {
  Americans: 'lincoln',
  Arabs: 'saladin',
  Aztecs: 'Aztec',
  Chinese: 'mao',
  Egyptians: 'cleopatra',
  England: 'Elizabeth',
  French: 'Napoleon',
  Germans: 'bismarck',
  Greeks: 'alexander',
  Indians: 'gandhi',
  Japanese: 'japanese',
  Mongols: 'Genghis',
  Romans: 'caesar',
  Russians: 'catherine',
  Spanish: 'isabella',
  Zulu: 'Zulu',
}

/** The five player colours the leader artwork comes in. */
const LEADER_COLOURS = new Set(['blue', 'green', 'purple', 'red', 'yellow'])

/**
 * The leader marker for a civilization in a player's colour, or undefined when
 * either is unknown. White has no leader artwork — it is the barbarian colour
 * and no player takes it.
 */
export function leaderAssetId(civName: string, color: string): string | undefined {
  const leader = LEADER_BY_CIV[civName]
  const colour = color.toLowerCase()
  if (leader === undefined || !LEADER_COLOURS.has(colour)) return undefined
  return `leaders/${leader}_${colour}`
}

/**
 * The number on a Tile card to the file name of its image.
 *
 * The files are called tile01 through tile14, then tile15a through tile21a,
 * then tile22b through tile25b, and finally Tile26b and Tile27b. The suffixes
 * separate the expansions, so the lookup goes by the number in the name.
 */
const TILE_BY_NUMBER = new Map<number, string>(
  BOARD_ASSETS.filter((asset) => asset.category === 'tile')
    .map((asset) => {
      const digits = /(\d+)/.exec(asset.id)
      return digits === null ? null : ([Number(digits[1]), asset.id] as const)
    })
    .filter((entry): entry is readonly [number, string] => entry !== null),
)

export function tileAssetIdForNumber(tileNumber: number): string | undefined {
  return TILE_BY_NUMBER.get(tileNumber)
}

// ---------------------------------------------------------------------------
// Replaying history
// ---------------------------------------------------------------------------

const withoutPiece = (pieces: readonly BoardPiece[], pieceId: string): BoardPiece[] =>
  pieces.filter((piece) => piece.id !== pieceId)

const insertAt = (
  pieces: readonly BoardPiece[],
  index: number,
  piece: BoardPiece,
): BoardPiece[] => {
  const next = [...pieces]
  next.splice(Math.min(Math.max(index, 0), next.length), 0, piece)
  return next
}

/** Applies one change, moving the board forwards in time. */
export function applyChange(
  pieces: readonly BoardPiece[],
  change: BoardChange,
): readonly BoardPiece[] {
  switch (change.kind) {
    case 'place':
      return change.onTop ? [...pieces, change.piece] : [change.piece, ...pieces]
    case 'remove':
      return withoutPiece(pieces, change.piece.id)
    case 'move': {
      const piece = pieces.find((candidate) => candidate.id === change.pieceId)
      if (piece === undefined) return pieces
      return [...withoutPiece(pieces, piece.id), { ...piece, x: change.to.x, y: change.to.y }]
    }
    case 'rotate':
      return pieces.map((piece) =>
        piece.id === change.pieceId ? { ...piece, rotation: change.to } : piece,
      )
    case 'reorder': {
      const piece = pieces.find((candidate) => candidate.id === change.pieceId)
      if (piece === undefined) return pieces
      const rest = withoutPiece(pieces, piece.id)
      return change.toTop ? [...rest, piece] : [piece, ...rest]
    }
    case 'clear':
      return []
  }
}

/** Applies the inverse of one change, moving the board backwards in time. */
export function revertChange(
  pieces: readonly BoardPiece[],
  change: BoardChange,
): readonly BoardPiece[] {
  switch (change.kind) {
    case 'place':
      return withoutPiece(pieces, change.piece.id)
    case 'remove':
      return insertAt(pieces, change.index, change.piece)
    case 'move': {
      const piece = pieces.find((candidate) => candidate.id === change.pieceId)
      if (piece === undefined) return pieces
      return insertAt(withoutPiece(pieces, piece.id), change.fromIndex, {
        ...piece,
        x: change.from.x,
        y: change.from.y,
      })
    }
    case 'rotate':
      return pieces.map((piece) =>
        piece.id === change.pieceId ? { ...piece, rotation: change.from } : piece,
      )
    case 'reorder': {
      const piece = pieces.find((candidate) => candidate.id === change.pieceId)
      if (piece === undefined) return pieces
      return insertAt(withoutPiece(pieces, piece.id), change.fromIndex, piece)
    }
    case 'clear':
      return change.pieces
  }
}

/**
 * The pieces as they stood after `step` changes. Step 0 is the empty board
 * the game started from; `history.length` is the present.
 *
 * Replaying from scratch is cheap because the board is small, and it avoids
 * keeping a snapshot per change.
 */
export function piecesAtStep(
  history: readonly BoardHistoryEntry[],
  step: number,
): readonly BoardPiece[] {
  let pieces: readonly BoardPiece[] = []
  for (const entry of history.slice(0, Math.max(0, Math.min(step, history.length)))) {
    pieces = applyChange(pieces, entry.change)
  }
  return pieces
}
