<#
Copies the piece artwork from Civilization/Moderator into the web package and
writes a manifest with the real image sizes.

The manifest goes in the engine rather than the client, because the server has
to be able to check that a piece being placed really points at a known file.
Without it a client could send any string at all as an image reference.

The PNGs themselves land in packages/web/public/board/ so Vite serves them.
#>
param(
    [string] $Source = (Join-Path $PSScriptRoot '..\Civilization\Moderator'),
    [string] $WebPublic = (Join-Path $PSScriptRoot '..\packages\web\public\board'),
    [string] $Manifest = (Join-Path $PSScriptRoot '..\packages\engine\data\board-assets.json')
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

# Source folder -> palette category. Tiles split in two because they are used
# differently: civtile is a starting tile, tile is a numbered exploration tile.
$categories = [ordered] @{
    'figures'   = 'figure'
    'resources' = 'resource'
    'markers'   = 'marker'
    'cities'    = 'city'
    'buildings' = 'building'
    'tiles'     = 'tile'
}

# A map tile covers 4 x 4 squares of 94 pixels. The source images are 375 x 375,
# so one pixel narrow; they are scaled to 376 to line up with the grid.
$TILE_PIXELS = 376

# The civilisations starting tiles. The rest of tiles/ are exploration tiles.
$civTiles = @(
    'america', 'arabia', 'Aztec', 'china', 'egypt', 'England', 'France', 'germany',
    'greece', 'india', 'japan', 'mongolia', 'rome', 'russia', 'spain', 'Zulu'
)

$colours = @('blue', 'green', 'purple', 'red', 'yellow', 'white')

function Get-Label([string] $category, [string] $baseName) {
    $name = $baseName

    if ($category -eq 'figure' -or $category -eq 'city') {
        # "redcapitalwalled2" -> colour plus the rest
        $colour = $colours | Where-Object { $name.StartsWith($_) } | Select-Object -First 1
        if ($null -ne $colour) {
            $rest = $name.Substring($colour.Length) -replace '\d+$', ''
            $walled = $rest.EndsWith('walled')
            if ($walled) { $rest = $rest.Substring(0, $rest.Length - 'walled'.Length) }
            $label = (Get-Culture).TextInfo.ToTitleCase($colour) + ' ' + $rest
            if ($walled) { $label += ' (walled)' }
            return $label.Trim()
        }
    }

    # "Building Program" and "coin1" -> "Building Program", "Coin 1"
    $spaced = ($name -creplace '([a-z])([A-Z0-9])', '$1 $2')
    return (Get-Culture).TextInfo.ToTitleCase($spaced.ToLower()) -replace '\s+', ' '
}

$assets = @()

foreach ($folder in $categories.Keys) {
    $category = $categories[$folder]
    $from = Join-Path $Source $folder
    if (-not (Test-Path $from)) { throw "Could not find $from" }

    $to = Join-Path $WebPublic $folder
    New-Item -ItemType Directory -Path $to -Force | Out-Null

    # -Include needs a wildcard in the path, so filter on Extension instead
    $files = Get-ChildItem $from -File | Where-Object { $_.Extension -in '.png', '.jpg' }
    foreach ($file in $files) {
        Copy-Item $file.FullName (Join-Path $to $file.Name) -Force

        $image = [System.Drawing.Image]::FromFile($file.FullName)
        try {
            $thisCategory = $category
            $width = $image.Width
            $height = $image.Height

            if ($category -eq 'tile') {
                if ($civTiles -contains $file.BaseName) { $thisCategory = 'civtile' }
                # Every map tile covers exactly 4 x 4 squares whatever its source size
                $width = $TILE_PIXELS
                $height = $TILE_PIXELS
            }

            $assets += [ordered] @{
                id       = "$folder/$($file.BaseName)"
                category = $thisCategory
                # The path the client loads from, relative to /board/
                path     = "$folder/$($file.Name)"
                label    = Get-Label $thisCategory $file.BaseName
                width    = $width
                height   = $height
            }
        } finally {
            $image.Dispose()
        }
    }

    Write-Host ("  {0,-10} {1,3} files" -f $folder, (Get-ChildItem $to -File).Count)
}

$payload = [ordered] @{
    note   = 'Generated by tools/board-assets.ps1. Do not edit by hand.'
    source = 'Civilization/Moderator'
    assets = $assets
}

New-Item -ItemType Directory -Path (Split-Path $Manifest) -Force | Out-Null
$json = $payload | ConvertTo-Json -Depth 6
[System.IO.File]::WriteAllText(
    (New-Item -ItemType File -Path $Manifest -Force).FullName,
    $json + "`n",
    (New-Object System.Text.UTF8Encoding($false)))

Write-Host "`nWrote $($assets.Count) pieces to $Manifest"
